#!/bin/bash

# 
# dotfiles installer
# 
#
# 使い方:
#
# $ DOTPATH=dot_repo \
#     DOTFILES_REPOS_URI=../../dot.dotfiles_demo.git \
#     DEPLOY_DIR=./deploy-dir \
#     bash -c "$(cat install)" -s init
# $ bash -c "$(cat install)" -s init
# $ bash -c "$(cat install)"
# $ bash -c "$(curl -L dot.tbrook.net)"
# $ curl -L dot.tbrook.net | bash
#


: "${DOTPATH:=${HOME}/.dotfiles}"
export DOTPATH

: "${DOTFILES_REPOS_URI:=https://github.com/tbrook/dotfiles.git}"
export DOTFILES_REPOS_URI

: "${DOTFILES_TARBALL_URI:=https://github.com/tbrook/dotfiles/archive/master.tar.gz}"


if [ -d "${DEPLOY_DIR:=${HOME}}" ]; then
    DEPLOY_APATH=$(cd "$DEPLOY_DIR" && pwd)
else
    log_fail "$DEPLOY_DIR: not found"
    exit 1
fi


dotfiles_logo='
###
### dotfiles install
###
'




e_newline() {
    printf "\n"
}

e_header() {
    printf " \033[37;1m%s\033[m\n" "$*"
}

e_error() {
    printf " \033[31m%s\033[m\n" "✖ $*" 1>&2
}

e_warning() {
    printf " \033[31m%s\033[m\n" "$*"
}

e_done() {
    printf " \033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

e_arrow() {
    printf " \033[37;1m%s\033[m\n" "➜ $*"
}


ink() {
    if [ "$#" -eq 0 -o "$#" -gt 2 ]; then
        echo "Usage: ink <color> <text>"
        echo "Colors:"
        echo "  black, white, red, green, yellow, blue, purple, cyan, gray"
        return 1
    fi

    local open="\033["
    local close="${open}0m"
    local black="0;30m"
    local red="1;31m"
    local green="1;32m"
    local yellow="1;33m"
    local blue="1;34m"
    local purple="1;35m"
    local cyan="1;36m"
    local gray="0;37m"
    local white="$close"

    local text="$1"
    local color="$close"

    if [ "$#" -eq 2 ]; then
        text="$2"
        case "$1" in
            black | red | green | yellow | blue | purple | cyan | gray | white)
            eval color="\$$1"
            ;;
        esac
    fi

    printf "${open}${color}${text}${close}"
}


logging() {
    if [ "$#" -eq 0 -o "$#" -gt 2 ]; then
        echo "Usage: ink <fmt> <msg>"
        echo "Formatting Options:"
        echo "  TITLE, ERROR, WARN, INFO, SUCCESS"
        return 1
    fi

    local color=
    local text="$2"

    case "$1" in
        TITLE)
            color=yellow
            ;;
        ERROR | WARN)
            color=red
            ;;
        INFO)
            color=blue
            ;;
        SUCCESS)
            color=green
            ;;
        *)
            text="$1"
    esac

    timestamp() {
        ink gray "["
        ink purple "$(date +%H:%M:%S)"
        ink gray "] "
    }

    timestamp; ink "$color" "$text"; echo
}

log_pass() {
    logging SUCCESS "$1"
}

log_fail() {
    logging ERROR "$1" 1>&2
}

log_fail() {
    logging WARN "$1"
}

log_info() {
    logging INFO "$1"
}

log_echo() {
    logging TITLE "$1"
}

# is_exists returns true if executable $1 exists in $PATH
is_exists() {
    which "$1" >/dev/null 2>&1
    return $?
}

# is_debug returns true if $DEBUG is set
is_debug() {
    if [ "$DEBUG" = 1 ]; then
        return 0
    else
        return 1
    fi
}


dotfiles_initialize() {
    if [ "$1" = "init" ]; then
        e_newline
        e_header "Initializing dotfiles..."

        if is_debug; then
            :
        else
            if [ -f Makefile ]; then
                #DOTPATH="$(dotpath)"
                #export DOTPATH
                #bash "$DOTPATH"/etc/init/init.sh
                make init
            else
                log_fail "Makefile: not found"
                exit 1
            fi
        fi &&

            e_newline && e_done "Initialize"
    fi
}



# 
tb.dotfiles_download() {
    if [ -d "$DOTPATH" ]; then
        log_fail "$DOTPATH: already exists"
        exit 1
    fi

    e_newline
    e_header "Downloading dotfiles..."

    if is_debug; then
        :
    else
        if is_exists "git"; then
            # --recursive equals to ...
            # git submodule init
            # git submodule update

	    git clone --recursive "$DOTFILES_REPOS_URI" "$DOTPATH"

        elif is_exists "curl" || is_exists "wget"; then
            # curl or wget

            if is_exists "curl"; then
##                curl -L "$tarball"
##                curl -L "$DOTFILES_TARBALL_URI"
:
            elif is_exists "wget"; then
##                wget -O - "$tarball"
##		wget -O - "$DOTFILES_TARBALL_URI"
:
##            fi | tar xvz
fi

            if [ ! -d dotfiles-master ]; then
                log_fail "dotfiles-master: not found"
                exit 1
            fi
            command mv -f dotfiles-master "$DOTPATH"

        else
            log_fail "curl or wget required"
            exit 1
	fi
    fi
    e_newline && e_done "Download"
}



tb.cd_dotpath() {
    if [ ! -d "$DOTPATH" ]; then
        log_fail "$DOTPATH: not found"
        exit 1
    else
	e_newline
	e_header "Change directory \$DOTPATH: '$DOTPATH'"
    fi

    command cd "$DOTPATH"
}


tb.dotfiles_deploy() {
    if [ ! -d "$DEPLOY_APATH" ]; then
        log_fail "$DEPLOY_APATH: not found"
    	exit 1
    fi

    e_newline
    e_header "Deploying dotfiles..."

    if is_debug; then
        :
    else
	make DEPLOY_DIR="$DEPLOY_APATH" deploy
    fi &&

        e_newline && e_done "Deploy"
}



tb.dotfiles_initialize() {
    dotfiles_initialize "$@"
}



# A script for the file named "install"
tb.dotfiles_install() {
    # 1. Download the repository
    # ==> downloading
    #
    # Priority: git > curl > wget
    tb.dotfiles_download &&

    # change directory to $DOTPATH
    tb.cd_dotpath &&

    # 2. Deploy dotfiles to your home directory
    # ==> deploying
    tb.dotfiles_deploy &&

    # 3. Execute all sh files within etc/init/
    # ==> initializing
    tb.dotfiles_initialize "$@"
}



# 
tb.is_bash() {
    [ -n "${BASH_VERSION-}" ]
}


# 
tb.is_zsh() {
    [ -n "${ZSH_VERSION-}" ]
}


# 
tb.sh_name() {
    if tb.is_bash; then
	echo 'bash'
    elif tb.is_zsh; then
	echo 'zsh'
    elif [ -n "${RANDOM-}" ]; then
	echo 'ksh'
    else
	echo 'other'
    fi
}




if echo "$-" | grep -q "i"; then
    e_warning "インタラクティブシェル では実行出来ません"
    exit 1
fi


case "$(tb.sh_name)" in
    bash* )
	if [ "$0" = "${BASH_SOURCE:-}" ]; then
	    e_warning "bash $0 では実行出来ません"
	    exit 1
	fi

	# -> bash -c "$(cat a.sh)"
	# -> cat a.sh | bash
	if [ -n "${BASH_EXECUTION_STRING:-}" ] || [ -p /dev/stdin ]; then
	    trap "echo 'terminated'; exit 1" INT ERR;

	    e_header "$dotfiles_logo"
            tb.dotfiles_install "$@"

            # Restart shell if specified "bash -c $(curl -L {URL})"
            # not restart:
            #   curl -L {URL} | bash
            if [ -p /dev/stdin ]; then
		e_warning "Now continue with Rebooting your shell"
            else
		e_newline
##		e_arrow "Restarting your shell..."
##		exec "${SHELL:-/bin/zsh}"
		e_warning "Now continue with Rebooting your shell"
            fi
	fi
	;;
    zsh* )
	echo "bash で実行して下さい" ;;
    * )
	echo "bash で実行して下さい" ;;
esac
